language: node_js
node_js:
  - "9.3.0"

sudo: required

# env:
#   - DOCKER_USER:
#     - secure:
#   - DOCKER_PASS:
#     - secure:

services:
  - docker

# Install dependencies for each module and build docker images
install:
  - yarn install

# Build the images to test against
before_script:
  - yarn build

# Run test suites against built images
script:
  - yarn unit-test
  - yarn integration-test

# Set git status and push images
after_success:
  - echo "success, set git status"
  - echo "TODO docker login and yarn deploy"

# After failure
after_failure:
  - echo "failure, set git status"
