version: '3'
services:
  db-service:
    build: ./db-service
    volumes:
      - ./db-service:/usr/src/db-service
    ports:
      - "3000:3000"
    depends_on:
      - rethinkdb
    networks:
      testing_net:
        ipv4_address: 172.28.1.1

  rethinkdb:
    build: ./rethinkdb
    ports:
      - "8080:8080"
    networks:
      testing_net:
        ipv4_address: 172.28.1.2

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
